name: 'Shortcut Release Action'
description: 'Add release note to release ticket and update related ticekts'
author: 'Allen Wei'
inputs:
  release_name:
    required: true
    description: 'Github release name'
  workflow:
    required: true
    description: 'Shorcut workflow name'
  workflow_state:
    required: true
    description: 'Shorcut workflow state name'
  release_ticket_id:
    required: true
    description: 'Shortcut release ticket id'
runs:
  using: 'node12'
  main: 'lib/main.js'
